version: '3.8'
services:
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3306:3306"
  
  myadmin:
    image: phpmyadmin:5.2
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
  
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
